### ISSUE TITLE
ansible.builtin.include has been removed. 

### ISSUE THREAD

**Issue by pavlozt** [AcroMedia/ansible-role-dkim#7]
I inform you that in modern versions of Ansible it is no longer possible to use include.

Here is errors when running this role:

> Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.

we need update role to using include_task instead of include

**Comment by dale-c-anderson** [comment]
Fixed by #8
